project:
  type: website

website:
  title: "Gentian Gashi"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/gentiang
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

